### ISSUE TITLE
Extension to input processing with ce 

### ISSUE THREAD

**Issue by polyluxus** [GaurangTandon/MarkdownShortcutsForSE#11]
In #5 you have added support for some weird input formats. I just came across the following abomination:  
`(CH$_{3}$)$_{3}$CI` 
Can you add this kind to the recognised patterns, i.e. producing `$\ce{(CH3)3CI}$`?

**Comment by polyluxus** [comment]
Sometimes I find weird stuff like `--->` and even `====>` which doesn't translate to anything useful in mhchem. Can we remove such patterns with with `->` preemptively. (It'll definitely be less garbage after the transformation than before.)

**Comment by GaurangTandon** [comment]
Sorry for the delay, this has been successfully added in v1.7.0.
