### ISSUE TITLE
Add metas to mhchem sites

### ISSUE THREAD

**Issue by polyluxus** [GaurangTandon/MarkdownShortcutsForSE#15]
I can reproduce #6 and this is due to me testing everything in the meta sandbox.

Ergo [L55](https://github.com/GaurangTandon/MarkdownShortcutsForSE/blob/a92cddb3917a8bca949683ee3dac5c70295b0e21/MarkdownShortcutsSE.user.js#L55) 
```
MHCHEM_SITE_REGEX = /(chemistry|biology)\.stackexchange/,
```
needs to include the meta sites, i.e.
```
MHCHEM_SITE_REGEX = /(chemistry|biology)(\.meta)?\.stackexchange/,
```
should do the trick.

**Comment by GaurangTandon** [comment]
Whoops, how could I miss that! :O Thanks, fixed :)
