### ISSUE TITLE
Back-forth arrow gets transformed to mesomeric arrow

### ISSUE THREAD

**Issue by polyluxus** [GaurangTandon/MarkdownShortcutsForSE#16]
`A <--> B`

<kbd>alt</kbd> + <kbd>e</kbd>

`\ce{A <-> B}`

should be

`\ce{A <--> B}`

Considerations for standardising, assume that mesomeric arrows are seldom used in reaction equations (different for schemes):

| input | standardised output |
|---|:---:|
| `<->` (single minus) | `<->` |
| `<-->` (double minus)| `<-->` |
| `<--->` (multiple, *any number* minus) | `<-->` |
| `<- ->` (multiple spaces)| `<-->` |
| `<===>` (multiple, *any number* equals)| `<=>` |

**Comment by GaurangTandon** [comment]
Thanks, fixed in v1.7.2.

**Test input:**

```
Both sided single arrows  
<->  
<-->  
<--->  
<- ->

Both sided double arrows  
<=>  
<=>  
<===>  

One sided single arrows:  
<-  
<----  
->  
--->  

One sided double arrows:  
<=  
<==  
=>  
===> 
```
