### ISSUE TITLE
Convert % to \% when applying maths

### ISSUE THREAD

**Issue by polyluxus** [GaurangTandon/MarkdownShortcutsForSE#18]
Problem for example for units that contain percents:

`10 wt%` <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>w</kbd> `$\pu{1 wt%}$`  
MathJax error: *Extra open brace or missing close brace*

This is due to the fact that even MathJax treats `%` for comments, i.e. the closing brace is missing.

In cases where `$` are to be applied it would be best to also automagically transform `%` to the escaped version `\%`, i.e.  

- `10 wt%` <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>w</kbd> `$\pu{1 wt\%}$`  
- `10%` <kbd>alt</kbd> + <kbd>z</kbd> or <kbd>c</kbd> `$10\%$` or `$$10\%$$`
- ```
  a=10%
  b=20%
  c=x%
  ```
  <kbd>alt</kbd> + <kbd>a</kbd>
  ```
  \begin{align}
  a&=10\%\\
  b&=20\%\\
  c&=x\%
  \end{align}
  ```

If it really is a comment (not many will use them), I think removing the backslash is the lesser evil than trying to find the error (if the maths get long).

**Comment by polyluxus** [comment]
I am tacking this on because the implementation is probably quite related.

Let's also remove `&nbsp;` when applying <kbd>alt</kbd> + <kbd>w</kbd>, i.e.  
`10&nbsp;mL` <kbd>alt</kbd> + <kbd>w</kbd> `\pu{10 mL}`

**Comment by GaurangTandon** [comment]
When do you want the `&nbsp;` to be removed? Only on `alt`-`w` or in general on all curly brace commands?

**Comment by polyluxus** [comment]
It's a html entity, it would produce errors in any mathjax context (except `\text{}` probably). But if you want to be on the save side, the mhchem macros would be sufficient.
