### ISSUE TITLE
Let fracify insert empty template

### ISSUE THREAD

**Issue by polyluxus** [GaurangTandon/MarkdownShortcutsForSE#19]
Instead of first writing `A/B` to convert <kbd>alt</kbd> + <kbd>s</kbd> to `\frac{A}{B}` I'd like to use <kbd>alt</kbd> + <kbd>s</kbd> to insert `\frac{|}{}` (`|` = cursor) to start typing the fraction. This would be consistent with the behaviour of <kbd>alt</kbd> + <kbd>w</kbd>/<kbd>e</kbd>/<kbd>r</kbd>/<kbd>t</kbd>.

**Comment by GaurangTandon** [comment]
Nice suggestion, added! Now you can press Ctrl-Alt-S, or alt-S, to get empty frac templates when no text is selected. It also unwraps nicely, as is consistent with other alt-inserts.

**Comment by polyluxus** [comment]
With the unwrapping you refer to the empty template, which works nicely, but as  
`A/B` <kbd>alt</kbd> + <kbd>s</kbd> `\frac{A}{B}` <kbd>alt</kbd> + <kbd>s</kbd> `\frac{A}{B}`  
does not unwrap, I suppose this is still the open enhancement #12.

Related, but I didn't think of this earlier, can we also have  
`]AB[` <kbd>alt</kbd> + <kbd>s</kbd> `\frac{AB}{|}` (`]...[` selection, `|` cursor)?
