### ISSUE TITLE
Popup for current hotkey bindings

### ISSUE THREAD

**Issue by polyluxus** [GaurangTandon/MarkdownShortcutsForSE#2]
It's easy to loose track on keyboard shortcuts, especially if you don't use them often.

In analogy to the stack exchange shortcuts (see [preferences](https://chemistry.stackexchange.com/users/preferences/), press <kbd>?</kbd> if enabled), I'd suggest to implement <kbd>Alt</kbd>+<kbd>?</kbd> as a way to make an info popup appear showing the current hotkey settings.

**Comment by GaurangTandon** [comment]
Here's how it looks like at the moment:

![image](https://user-images.githubusercontent.com/6308683/44984913-12cd3f00-af9c-11e8-8d38-d91e84a6572f.png)

Please let me know if that's satisfactory or there are some changes required. This popup can be toggled with the simple trigger `Alt + ?`, as you suggested.

Commits: [first](https://github.com/GaurangTandon/MarkdownShortcutsForSE/commit/afe4dd3cbfe3661d080ad0f4852461002b96fe30) and [second](https://github.com/GaurangTandon/MarkdownShortcutsForSE/commit/0b09fc7606a36ac9019b920cbf209afc67eca0d3).

**Comment by polyluxus** [comment]
Unfortunately that doesn't work for me ( ; __ ; ); it could be my German keyboard. Maybe alias in `Alt + h` for help for non US-layouts?

**Comment by GaurangTandon** [comment]
That's odd. If the other keys work then this should too. You also pressed the Shift key, didn't you? The actual hotkey is `Alt + Shift + ?`. I didn't mention the Shift key because without it you would be pressing `Alt + /` instead. Please try once again. Thanks.

**Comment by polyluxus** [comment]
Yeah, it's `Alt + Shift + ß` on mine, but nothing happens. 

Definitely a locale problem, if I switch to English, it works as expected.

**Comment by GaurangTandon** [comment]
Shortcut changed to `Alt-H`
