### ISSUE TITLE
(double) dollarify should recognise \ce, \mathrm, ...

### ISSUE THREAD

**Issue by polyluxus** [GaurangTandon/MarkdownShortcutsForSE#3]
For example
A, mark,  <kbd>Alt</kbd>+<kbd>z</kbd>, <kbd>Alt</kbd>+<kbd>e</kbd> => `$\ce{A}$`  
A, mark,  <kbd>Alt</kbd>+<kbd>e</kbd>, <kbd>Alt</kbd>+<kbd>z</kbd> => `\ce{$A$}`  
It would be better if (double) dolarify would recognise a 'LaTeX' syntax and wraps the dollars around it.

**Comment by GaurangTandon** [comment]
Do you mean to say that "A, mark,  <kbd>Alt</kbd>+<kbd>e</kbd>, <kbd>Alt</kbd>+<kbd>z</kbd>" should output `$\ce{a}$` instead of `\ce{$a$}`?

**Comment by polyluxus** [comment]
Yes, I think that would be good.  
When you use fracify, then after it is applied, the whole command is marked, maybe you could do it the same for `\ce{...}`, `\mathrm{...}`, `\pu{...}`, and maybe others I cannot think of now.  
I have not had a look at the source yet, so I couldn't comment on what could or could not be done...

**Comment by GaurangTandon** [comment]
That would be a bit tough. It goes along a desire path but again it can be self-contradictory.

Supposing this feature is implemented, how would you then, for example, insert `$$` inside of `\tag{}`? The userscript would automatically detect the two braces and output `$\tag{|}$` (`|`=caret), making it impossible to type `\tag{$$}`.

Again, I agree with the sentiment that you rarely need `\ce{$$}` as compared to `$\ce{}$`, so "out-formatting" (is that a word?) the dollar signs should be plausible. 

How about I implement this only for a certain set of LaTeX commands, like `frac`, `ce`, `pu`, and `mathrm`?

**Comment by polyluxus** [comment]
Maybe it really would be best to just shift the focus, i.e. like with fracify you have `a/a` and you transform it to `\frac{a}{a}`, where all is highlighted (but it cannot be reversed), you can easily apply dollarify to the whole expression.  
So basically after applying `ce`, you end up with the whole thing highlighted and then just wrap it in dollars if you want. That way it wouldn't disturb the usage of dollar signs within those constructs, if that's necessary. I hope I'm making myself clear here...

**Comment by GaurangTandon** [comment]
>Maybe it really would be best to just shift the focus, 

<nod> ...however, I had a reason to apply focus to inside the `{}`. For example, you have `a|bc|`. You apply Alt-E, we get `a\ce{|bc|}`. Now, you can directly press `delete` key on the selection and type whatever you want. Or, you can press the arrow keys to type before or after the contents.

However, this is not possible if after applying `ce`, you end with `a|\ce{bc}|`. Thoughts?

**Comment by polyluxus** [comment]
I see your point, I guess I simply use it differently; i.e. different workflow. For example I would first write or change the formula, then I would apply the MathJax commands, then I would apply the dollars to actually render it. Meaning, I want it to not render as MathJax as long as possible. That is currently only possible when you reapply focus.   
With these different styles of usage, come obviously different problems. While for me alt+e, alt+z is the natural workflow, it is apparently not for you. I simply, currently have no cure for this issue.

**Comment by polyluxus** [comment]
I completely overlooked, that you can do  
A, mark,  <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>e</kbd> => `$\ce{A}$`,  
which solves my problem, when I have gotten used to it.

I think you should label this *nofix*/*wontfix*, and I'm closing this now, as it is not really an issue with the script (it does what it should), but with the user.

**Comment by GaurangTandon** [comment]
I had assumed you knew about that shortcut already ._. Nvm
