### ISSUE TITLE
Avoid double braces

### ISSUE THREAD

**Issue by polyluxus** [GaurangTandon/MarkdownShortcutsForSE#7]
Currently, when a braced construct is selected, it unnecessarily inserts another pair of braces:  
`{a}` <kbd>alt</kbd>+<kbd>R</kbd> `\mathrm{{a}}`.  
Not that the double braces would hurt, but it would be better (I guess) not to insert extras:  
`{a}` <kbd>alt</kbd>+<kbd>R</kbd> `\mathrm{a}`.

Note that in the case where you only select the inner part, (using `|` for delimitation here) it produces valid syntax:  
`{|a|}` <kbd>alt</kbd>+<kbd>R</kbd> `{\mathrm{a}}`.

I think that can be extended to `\text{...}`, `\ce{...}` and `\pu{...}`, too.

**Comment by GaurangTandon** [comment]
Please check out the updated version, and let me know if it works as expected.
