### ISSUE TITLE
substitute latex arrow commands with mhchem recognised equivalents

### ISSUE THREAD

**Issue by polyluxus** [GaurangTandon/MarkdownShortcutsForSE#9]
Wouldn't it be brilliant if
`A+B\rightarrow C` would automagically <kbd>Alt</kbd> + <kbd>e</kbd> transform into `\ce{A + B -> C}`?

What should be inserted according to [doc](https://mhchem.github.io/MathJax-mhchem/)

| mhchem code | possibly used |
| ----------- | ------------- |
| `->`        | `\rightarrow`, `\longrightarrow`, unicode(s) |
| `<-`        | `\leftarrow`, `\longleftarrow`, unicode(s) |
| `<->`       | `\leftrightarrow`, `\longleftrightarrow`, unicode(s) |
| `<-->`      | n/a |
| `<=>`       | `\leftrightharpoons`, `\rightleftharpoons`, unicode(s) |
| `<=>>`      | n/a  |
| `<<=>`      | n/a |

**Comment by GaurangTandon** [comment]
Nice idea! Please refer to the following test case to make sure the new addition in v1.4.0 works as intended.

**Test case:**

    A \leftarrow \longleftarrow &#8592; &larr; ← B  
    A \rightarrow \longrightarrow &#8594; &rarr; → B  
    A \leftrightarrow \leftrightarrow &#8596; &harr; ↔ B  
    A \leftrightharpoons \rightleftharpoons &#8660; &hArr; ⇔ B  

should transform to (press `Alt` + `E` on each line):

```
\ce{A <- <- <- <- <- B}  
\ce{A -> -> -> -> -> B}
\ce{A <-> <-> <-> <-> <-> B}  
\ce{A <=> <=> <=> <=> <=> B} 
```

**Comment by polyluxus** [comment]
Nicely done, but I fear something has broken in the meantime.  
After the transformation I used <kbd>Alt</kbd> + <kbd>a</kbd> with little success, see here

Input:
```
\ce{A <- <- <- <- <- B}  
\ce{A -> -> -> -> -> B}  
\ce{A <-> <-> <-> <-> <-> B}  
\ce{A <=> <=> <=> <=> <=> B}  
```
Output:
```
\begin{align}
\ce{A &<- &<- &<- &<- &<- B}\\
\ce{A -&> -&> -&> -&> -&> B}\\
\ce{A &<-&> &<-&> &<-&> &<-&> &<-&> B}\\
\ce{A &<=&> &<=&> &<=&> &<=&> &<=&> B}
\end{align}  
```
It seems that the insertion of the `&` does no longer recognises these symbols and inserts too many. Not like it was intended as discussed in [#5](https://github.com/GaurangTandon/MarkdownShortcutsForSE/issues/5#issuecomment-418734823).
